name: Build ICS

on:
  push:
    branches: [ "main" ]
    paths:
      - "calendar_template.xlsx"
      - "generate_ics.py"
      - "**/*.xlsx"
      - "**/*.py"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl

      - name: Generate ICS
        run: |
          python generate_ics.py --xlsx calendar_template.xlsx --out docs/calendar.ics

      - name: Commit ICS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/calendar.ics
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-build calendar.ics"
            git push
          fi
